import { Employee, EmailMessage } from './types';

export const mockEmployees: Employee[] = [
  {
    id: '1',
    name: 'Sarah Johnson',
    email: 'sarah.johnson@company.com',
    position: 'Senior Developer',
    department: 'Engineering',
    joinDate: '2022-03-15',
  },
  {
    id: '2',
    name: 'Michael Chen',
    email: 'michael.chen@company.com',
    position: 'Product Manager',
    department: 'Product',
    joinDate: '2021-07-22',
  },
  {
    id: '3',
    name: 'Emily Rodriguez',
    email: 'emily.rodriguez@company.com',
    position: 'UX Designer',
    department: 'Design',
    joinDate: '2023-01-10',
  },
  {
    id: '4',
    name: 'James Wilson',
    email: 'james.wilson@company.com',
    position: 'DevOps Engineer',
    department: 'Infrastructure',
    joinDate: '2021-11-05',
  },
  {
    id: '5',
    name: 'Lisa Anderson',
    email: 'lisa.anderson@company.com',
    position: 'Marketing Manager',
    department: 'Marketing',
    joinDate: '2022-06-18',
  },
  {
    id: '6',
    name: 'David Brown',
    email: 'david.brown@company.com',
    position: 'Data Analyst',
    department: 'Analytics',
    joinDate: '2023-04-01',
  },
];

export const mockEmailMessages: EmailMessage[] = [
  {
    id: '1',
    messageId: 'MSG-2024-001',
    employeeIds: ['1', '2', '3'],
    subject: 'Q4 Performance Review Scheduled',
    content: 'Your performance review is scheduled for next week. Please prepare your achievements and feedback.',
    sentAt: '2024-07-15T10:30:00',
    status: 'sent',
  },
  {
    id: '2',
    messageId: 'MSG-2024-002',
    employeeIds: ['1', '4', '5', '6'],
    subject: 'Team Building Event - Friday',
    content: 'Join us for our quarterly team building event this Friday at 5 PM.',
    sentAt: '2024-07-12T14:15:00',
    status: 'sent',
  },
  {
    id: '3',
    messageId: 'MSG-2024-003',
    employeeIds: ['2', '3'],
    subject: 'Project Kickoff Meeting',
    content: 'We are excited to start the new project. Meeting details will be sent separately.',
    sentAt: '2024-07-08T09:00:00',
    status: 'sent',
  },
  {
    id: '4',
    messageId: 'MSG-2024-004',
    employeeIds: ['1', '2', '3', '4', '5', '6'],
    subject: 'Company Policy Update',
    content: 'Please review the updated company policies in your employee portal.',
    sentAt: '2024-06-28T11:45:00',
    status: 'sent',
  },
  {
    id: '5',
    messageId: 'MSG-2024-005',
    employeeIds: ['4'],
    subject: 'Server Maintenance Scheduled',
    content: 'Scheduled maintenance on servers will occur on Saturday at midnight.',
    sentAt: '2024-06-15T16:20:00',
    status: 'sent',
  },
];
